services:
  - type: web
    name: burrowspace-libp2p-server
    env: node
    nodeVersion: 18.17.1
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
    plan: free
    healthCheckPath: / 