services:
  - type: web
    name: burrowspace-libp2p-server
    env: node
    nodeVersion: 18.17.1
    buildCommand: npm install && npm rebuild && chmod +x render-start.sh
    startCommand: ./render-start.sh
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
    plan: free
    healthCheckPath: /status 