services:
  - type: web
    name: burrowspace-libp2p-server
    env: node
    buildCommand: cd libp2p_server && npm install
    startCommand: cd libp2p_server && npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 3000
    healthCheckPath: / 